openapi: 3.0.1
info:
  title: Documentação da API Jogoteca
  description: API para gerenciar uma biblioteca de jogos
  version: 1.0.0
paths:
  /:
    get:
      summary: Página inicial
      description: Retorna a página inicial da aplicação.
      responses:
        '200':
          description: OK
  /login:
    get:
      summary: Página de login
      description: Retorna a página de login.
      responses:
        '200':
          description: OK
  /autenticar:
    post:
      summary: Autenticação do usuário
      description: Autentica o usuário com as credenciais fornecidas.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                nickname:
                  type: string
                senha:
                  type: string
      responses:
        '302':
          description: Redirecionado para a próxima página após autenticação
        '401':
          description: Credenciais inválidas
  /logout:
    get:
      summary: Página de logout
      description: Realiza o logout do usuário.
      responses:
        '302':
          description: Redirecionado para a página inicial após o logout
  /cadastro:
    get:
      summary: Página de cadastro
      description: Retorna a página de cadastro de usuário.
      responses:
        '200':
          description: OK
  /criar_usuario:
    post:
      summary: Criação de usuário
      description: Cria um novo usuário com as informações fornecidas.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                nome:
                  type: string
                email:
                  type: string
                senha:
                  type: string
      responses:
        '302':
          description: Redirecionado para a página de perfil após o cadastro
  /perfil:
    get:
      summary: Página de perfil
      description: Retorna a página de perfil do usuário logado.
      responses:
        '200':
          description: OK
  /perfil/{usuario_id}:
    get:
      summary: Perfil do usuário
      description: Retorna o perfil do usuário com o ID especificado.
      parameters:
        - in: path
          name: usuario_id
          required: true
          description: ID do usuário
          schema:
            type: integer
      responses:
        '200':
          description: OK
  /jogo:
    get:
      summary: Página de lista de jogos
      description: Retorna a página com a lista de jogos disponíveis.
      responses:
        '200':
          description: OK
  /criar_jogo:
    get:
      summary: Página de criação de jogo
      description: Retorna a página para criar um novo jogo.
      responses:
        '200':
          description: OK
  /editar_jogo/{jogo_id}:
    get:
      summary: Página de edição de jogo
      description: Retorna a página para editar um jogo existente.
      parameters:
        - in: path
          name: jogo_id
          required: true
          description: ID do jogo
          schema:
            type: integer
      responses:
        '200':
          description: OK
  /deletar_jogo/{jogo_id}:
    get:
      summary: Exclusão de jogo
      description: Exclui o jogo com o ID especificado.
      parameters:
        - in: path
          name: jogo_id
          required: true
          description: ID do jogo
          schema:
            type: integer
      responses:
        '302':
          description: Redirecionado para a lista de jogos após a exclusão
  /lista_de_usuarios:
    get:
      summary: Página de lista de usuários
      description: Retorna a página com a lista de todos os usuários cadastrados.
      responses:
        '200':
          description: OK
